# Generated by Django 5.1.6 on 2025-02-07 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoreEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('initial_food', models.PositiveIntegerField(default=50)),
                ('initial_wood', models.PositiveIntegerField(default=50)),
                ('initial_stone', models.PositiveIntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('wood', 'Wood'), ('stone', 'Stone'), ('food', 'Food')], max_length=20)),
                ('quantity', models.FloatField(default=0)),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.settlement')),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_type', models.CharField(choices=[('lumber_mill', 'Lumber Mill'), ('quarry', 'Quarry'), ('farmhouse', 'Farmhouse')], max_length=20)),
                ('construction_progress', models.FloatField(default=0)),
                ('is_constructed', models.BooleanField(default=False)),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='core.settlement')),
            ],
        ),
        migrations.CreateModel(
            name='Settler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(default='idle', max_length=100)),
                ('mood', models.CharField(default='neutral', max_length=100)),
                ('hunger', models.IntegerField(default=0)),
                ('assigned_building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_settlers', to='core.building')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlers', to='core.settlement')),
            ],
        ),
    ]
