# Generated by Django 5.1.6 on 2025-02-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_settlement_initial_food_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick_count', models.IntegerField(default=0)),
                ('current_season', models.CharField(default='Spring', max_length=20)),
            ],
        ),
    ]
