# Generated by Django 5.1.6 on 2025-02-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_settlement_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='coordinate_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='coordinate_y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
