# Generated by Django 5.1.6 on 2025-02-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_eventlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='settler',
            name='birth_tick',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settler',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='settler',
            name='mood',
            field=models.CharField(choices=[('content', 'Content'), ('hungry', 'Hungry'), ('sick', 'Sick')], default='content', max_length=10),
        ),
        migrations.AlterField(
            model_name='settler',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('working', 'Working'), ('dead', 'Dead')], default='idle', max_length=10),
        ),
    ]
