# Generated by Django 5.1.6 on 2025-02-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_settler_birth_tick_settler_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
