# Generated by Django 5.1.6 on 2025-02-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_maptile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='building_type',
            field=models.CharField(choices=[('lumber_mill', 'Lumber Mill'), ('quarry', 'Quarry'), ('farmhouse', 'Farmhouse'), ('house', 'House'), ('warehouse', 'Warehouse')], max_length=20),
        ),
    ]
