# Generated by Django 5.1.6 on 2025-02-23 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_resourcenode'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcenode',
            name='gatherer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gathering_resource', to='core.settler'),
        ),
        migrations.AddField(
            model_name='settler',
            name='gathering_resource_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_gatherer', to='core.resourcenode'),
        ),
    ]
