# Generated by Django 5.1.6 on 2025-02-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_settler_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settler',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('working', 'Working'), ('gathering', 'Gathering'), ('dead', 'Dead')], default='idle', max_length=20),
        ),
    ]
