# Generated by Django 5.1.6 on 2025-02-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_settler_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='magic',
            field=models.IntegerField(default=0),
        ),
    ]
