# Generated by Django 5.1.6 on 2025-02-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_settlement_magic'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='happiness_boost',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='settlement',
            name='happy_duration',
            field=models.IntegerField(default=0),
        ),
    ]
