# Generated by Django 5.1.6 on 2025-03-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_settlement_happiness_boost_settlement_happy_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='event_type',
            field=models.CharField(choices=[('building_placed', 'Building Placed'), ('villager_assigned', 'Villager Assigned'), ('villager_hungry', 'Villager Hungry'), ('villager_dead', 'Villager Dead'), ('season_changed', 'Season Changed'), ('building_finished', 'Building Finished')], max_length=50),
        ),
    ]
